### ISSUE TITLE
KreditSmart Ereignisse

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-ereignisse-api#13]
Wäre es möglich diese API etwas zu verallgemeinern und damit sowohl das Auslesen von BaufiSmart, als auch das **Auslesen von KreditSmart- Ereignissen** zu ermöglichen? 

Die URL der API (https://api.europace.de/ ...) liesse dies nämlich vermuten.

APIs die lediglich Baufi-Ressourcen bereitstellen, beginnen hingegen allesamt mit: https://baufismart.api.europace.de/...

**Comment by Atrusberlin** [comment]
Hallo @ic-hv danke für den Hinweis. Ich werde das mit den Teams besprechen und hier ein Update geben.

**Comment by ollio** [comment]
So eine Anfrage gab es auch schon mal Richtung [Vorgänge API](https://github.com/europace/baufismart-vorgaenge-api).

**Comment by ic-hv** [comment]
> 
> 
> So eine Anfrage gab es auch schon mal Richtung [Vorgänge API](https://github.com/europace/baufismart-vorgaenge-api).

Hmm, ja da funktioniert es ja auch bereits ...

**Comment by Atrusberlin** [comment]
@ic-hv nach den aktuellen Kenntnissen bevorzuge ich das Ergänzen der Sub-Domain `baufismart`. Ich denke das werden wir als Major Update umsetzen, um keinen breaking change zu verursachen oder mehrere Endpunkte supporten zu müssen.

**Comment by ic-hv** [comment]
> 
> 
> @ic-hv nach den aktuellen Kenntnissen bevorzuge ich das Ergänzen der Sub-Domain `baufismart`. Ich denke das werden wir als Major Update umsetzen, um keinen breaking change zu verursachen oder mehrere Endpunkte supporten zu müssen.

Ok ... wichtiger wäre mir aber tatsächlich, auch für KreditSmart-Fälle Ereignisse abrufen zu können ... ist dies zeitnah umsetzbar?

**Comment by sgrell** [comment]
Soweit ich weiß steht eine Ereignis-API für Kreditsmart noch nicht auf unserer Roadmap, falls es diese API irgendwann gibt, dann ist es aber höchstwahrscheinlich eine eigenen API. Vielleicht könntest du euren Use-Case noch mal genauer erklären, damit wir es besser einordnen können.

Für Kreditsmart gibt es bereits eine [Push-API](https://github.com/europace/kex-push) die darüber informiert, dass es eine Änderung an einem Vorgang oder Antrag gab. Die Vorgangs- bzw. Antragsdaten können über den [Export](https://github.com/europace/kex-vorgang-export-api) abgerufen werden. Nicht jede Änderung ist auch gleich ein Ereignis und man kann eben "nur" den aktuellen Datensatz abrufen, nicht die Änderungen, aber evtl. reicht das für den Anwendungsfall.

**Comment by ic-hv** [comment]
Die Push- und Export-API sind mir bekannt. Unser Kunde hätte eben nur gerne auch Zugriff auf das Ereignis-Log für KreditSmart-Fälle. 
Hintergrund ist, das sämtliche auf Europace vorhandenen Fälle ins kundenseitige CRM synchronisiert werden und im kundenseitigen CRM nur ein(!) Interface für die Darstellung von sowohl BaufiSmart, als auch KreditSmart-Fällen verwendet wird. Das im BaufiSmart-Fall Ereignisse angezeigt werden können und im KreditSmart-Fall aber nicht, ist da leider etwas unbefriedigend ... auch mich als Programmierer verwundert die Uneinheitlichkeit der APIs für BaufiSmart einerseits und KreditSmart andererseits ... but well, that's life :)

**Comment by sgrell** [comment]
Danke für die Infos zum Anwendungsfall, sowas hilft uns immer die Prioritäten besser zu bewerten.

**Comment by Atrusberlin** [comment]
@ic-hv in der neuen Version der Ereignisse-API (v2 mit OAuth-Zugriff) haben wir deinen Vorschlag umgesetzt und die Ereignisse sind jetzt unter `baufismart.api.europace.de/v2/ereignisse` auffindbar.

Damit sehe ich das Issue als gelöst. Danke für Dein Feedback.
