### ISSUE TITLE
Dokumente-Links fehlen neuerdings

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-ereignisse-api#16]
Bis vor Kurzem wurden bei einem Abruf von Ereignissen zu einem Vorgang bsp.weise via https://baufismart.api.europace.de/v2/ereignisse/BY1PMB bei einem Ereignis mit **meldung** == "Dokument hochgeladen" auch ein Feld **dokumente** mitgeliefert, das die Links auf die hochgeladenen Dokumente gelistet hat. Dieses Feld fehlt nun neuerdings!

Würden Sie dieses Feld bitte wieder mit ausliefern - bzw. könnten Sie kurz beschreiben was zu tun ist, um diese Dokumenten-Links wieder auslesen zu können?

**Comment by uweelsholz** [comment]
Wie in der [README](https://github.com/europace/baufismart-ereignisse-api/blob/master/README.md#authentifizierung) beschrieben, ist dazu die Client-Berechtigung "Dokumente lesen" erforderlich.

Sollte das Problem weiterhin bestehen wären weitere Angaben hilfreich (z.B. PartnerId des Clients, Screenshot von den Client-Berechtigungen ...)

Viel Erfolg!

**Comment by ic-hv** [comment]
Achja, stimmt ... da war ja was ... im Zuge der Umstellung auf den "client credential" - Flow hatte ich nicht berücksichtigt in der API-Clients Lasche das entsprechende Recht zu vergeben ... 

Läuft jetzt! Danke vielmals!
