### ISSUE TITLE
Response Status 500 und 503

### ISSUE THREAD

**Issue by yahlers** [europace/baufismart-ereignisse-api#5]
Beim Auswerten unserer Vorgänge aus 2018 sind auf ca. 30% der Anfragen mit einen 500 oder 503 zurückgekommen. Woran es liegt können wir nicht sagen, aber sofern Beispiel-Vorgangsnummern gebraucht werden, sende ich dieses gerne per Mail.

**Comment by caspii** [comment]
Von QualityPool

**Comment by caspii** [comment]
@ollio kannst nur Dur das beheben oder könnte das auch Tina?

**Comment by caspii** [comment]
@ollio gibt es hier ein Update?

**Comment by yahlers** [comment]
Wir könnten nun nach der Anpassung die restlichen Ereignisse abfragen. Ich habe allerdings noch eine geringe Menge an Fehlern zu eher nicht relevanten Fällen. Das kurzgehaltenen Fehler-Log mit den jeweiligen Fällen habe ich an @MichaelKruegerHaubenschild gesendet.

**Comment by yahlers** [comment]
Das sollte Mike bewerten, da man noch den ein oder anderen 504 oder 403 Fehler erhält zu Fällen, die existieren und auch Ereignisse besitzen. Könnte je nach dem auch ein neuer Issue sein.

**Comment by caspii** [comment]
OK

**Comment by MikeKrueger75** [comment]
pls close
